### ISSUE TITLE
Send-service.py script not sending notifications for services containing a blank space in the name

### ISSUE THREAD

**Issue by MartijnLangohr** [Operator873/Nagios-Discord#1]
I'm not sure if you're still maintaining this project, but I've run into an issue with the send-service.py script.

I'm really happy I've found your code for Discord notifications, but the send-service.py doesn't seem to work for me when the service name contains a blank space, as already mentioned in the title. Looking at the Nagios logging, the send-service.py runs fine and doesn't return any errors - the logging simply tells me that a service notification has been send out. However, no message is seen in Discord.

**When do I see a message in Discord?**
I can see a message in Discord coming from Nagios when the service doesn't contain a blank space in it's name and the name is just a single word - for example "Sonarr"

**When do I not see a message in Discord?**
I cannot see a message in Discord coming from Nagios when the service does contain a blank space in it's name and the name exists of multiple words - for example "Ansible AWX"

The type of service check doesn't seem to have an impact as this behaviour is seen on services with the same check. Can you confirm that this is related (or not) to the send-service.py script?

**Comment by Operator873** [comment]
Hi @MartijnLangohr I don't use Nagios anymore after finding CheckMk (https://checkmk.com) a much better fit. However, I'm always open to checking issues. I'll see what I can figure out!

**Comment by Operator873** [comment]
@MartijnLangohr I pushed a general cleanup update just now but I have a suspicion that the issue lies in how Nagios calls the script itself:
```
command_line /usr/lib/nagios/plugins/send-service.py "$NOTIFICATIONTYPE$" "$SERVICEDESC$" "$HOSTNAME$" "$HOSTADDRESS$" "$SERVICESTATE$" "$TIMET$" "$SERVICEOUTPUT$"
```

In the script, I lazily matched item for item based on those spaces:
```python
data = {KEYS[i]: nag_in[i] for i in range(len(KEYS))}
``` 

Having spaces in the service name would likely mess this pairing up and the script would just exit. I don't handle errors at all or report anything so that may be why you don't see anything.

Short of a complete rebuild (which is hard to do since I don't run Nagios anymore), the best corrective action would be to rename your services to not include spaces. Perhaps "Ansible-AWX" or similar.

In the meantime, check out CheckMk. I don't work for them or anything and I like it enough to strongly recommend to anyone who'll listen.

**Comment by MartijnLangohr** [comment]
Hi @Operator873, thanks for replying and looking into it! I've checked out CheckMk and it seems like a nice solution to use for monitoring, I might migrate from Nagios to CheckMk in the near future. As you already recommended, I think renaming my services to not include a blank space is probably best for now.

Thanks again for responding and for the effort to create this notification plugin :)
